# pyrefly: ignore [missing-import]
from pydantic import BaseModel, Field


# ─── Profile ──────────────────────────────────────────────────────────────────


class NutritionProfile(BaseModel):
    """Normalised user profile produced by the Profile Agent."""

    age: int
    gender: str
    height_cm: float
    weight_kg: float
    goal: str  # normalised goal key e.g. "fat_loss"
    activity_level: str  # normalised key e.g. "moderate"
    diet_type: str
    preferences: list[str]
    allergies: list[str]
    additional_notes: str | None = None


# ─── Calories ─────────────────────────────────────────────────────────────────


class CaloriesResult(BaseModel):
    """Result of the deterministic calorie calculator."""

    bmr: float = Field(description="Basal Metabolic Rate (kcal/day)")
    tdee: float = Field(description="Total Daily Energy Expenditure (kcal/day)")
    target_calories: float = Field(
        description="Daily calorie target after goal adjustment"
    )
    formula_used: str = "Mifflin-St Jeor"
    goal: str
    activity_level: str
    # Pass-through profile fields needed by macro calculator
    weight_kg: float
    goal_adjustment_kcal: int


# ─── Macros ───────────────────────────────────────────────────────────────────


class MacroResult(BaseModel):
    """Daily macronutrient targets."""

    target_calories: float
    protein_g: float
    carbs_g: float
    fat_g: float
    goal: str
    weight_kg: float
    protein_per_kg: float
    # Pass-through for downstream agents
    diet_type: str
    preferences: list[str]
    allergies: list[str]


# ─── Meal Plan ────────────────────────────────────────────────────────────────


class MealFoodItem(BaseModel):
    """A food item within a meal with serving size."""

    name: str
    serving_grams: float
    calories: float
    protein_g: float
    carbs_g: float
    fat_g: float


class Meal(BaseModel):
    """A single meal (Breakfast, Lunch, Dinner, Snack)."""

    meal_name: str
    foods: list[MealFoodItem]
    total_calories: float
    total_protein_g: float
    total_carbs_g: float
    total_fat_g: float


class MealPlan(BaseModel):
    """Full daily meal plan produced by the Meal Composition Agent."""

    breakfast: Meal
    lunch: Meal
    dinner: Meal
    snack: Meal | None = None
    total_daily_calories: float
    total_daily_protein_g: float
    total_daily_carbs_g: float
    total_daily_fat_g: float
    notes: str | None = None


# ─── Per-Meal Distribution ────────────────────────────────────────────────────


class MealSlotTarget(BaseModel):
    """Calorie + macro budget for one meal slot."""

    meal_name: str        # e.g. "الإفطار"
    slot_key: str         # e.g. "breakfast"
    target_calories: float
    target_protein_g: float
    target_carbs_g: float
    target_fat_g: float


class MealDistribution(BaseModel):
    """Per-slot macro distribution derived from the daily MacroResult."""

    breakfast: MealSlotTarget
    lunch: MealSlotTarget
    dinner: MealSlotTarget
    snack: MealSlotTarget
    total_calories: float


# ─── Triple Meal Plan (3 Options) ─────────────────────────────────────────────


class TripleMealPlan(BaseModel):
    """Three independent full-day meal plan options generated by the iterative agent."""

    option_a: MealPlan
    option_b: MealPlan
    option_c: MealPlan
    meal_distribution: MealDistribution
    notes: str | None = None


# ─── Validation ───────────────────────────────────────────────────────────────


class ValidationIssue(BaseModel):
    rule: str
    expected: str
    actual: str
    severity: str = "error"  # "error" | "warning"


class ValidationReport(BaseModel):
    """Outcome of the deterministic nutrition validation engine."""

    passed: bool
    issues: list[ValidationIssue] = Field(default_factory=list)
    calorie_deviation_pct: float
    protein_deviation_pct: float
    carbs_deviation_pct: float
    fat_deviation_pct: float


# ─── Explanation ──────────────────────────────────────────────────────────────


class Explanation(BaseModel):
    """Human-readable explanation produced by the Explanation Agent."""

    summary: str
    calorie_rationale: str
    macro_rationale: str
    food_selection_rationale: str
    adherence_tips: list[str]
